### ISSUE TITLE
session_id is not set, is /proc mounted with hidepid>0?

### ISSUE THREAD

**Issue by hinxx** [the-cavalry/light-locker#169]
```
user@srv07:~$ xfce4-session --version
xfce4-session 4.18.3 (Xfce 4.18)

Copyright (c) 2003-2023
	The Xfce development team. All rights reserved.

Please report bugs to <https://gitlab.xfce.org/xfce/xfce4-session>.

user@srv07:~$ light-locker --version
light-locker 1.8.0

user@srv07:~$ gdb /usr/bin/light-locker 
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/light-locker...
(No debugging symbols found in /usr/bin/light-locker)
(gdb) r
Starting program: /usr/bin/light-locker 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5f70640 (LWP 841577)]
[New Thread 0x7ffff576f640 (LWP 841578)]
[New Thread 0x7fffeffff640 (LWP 841579)]

** (light-locker:841574): ERROR **: 13:32:16.859: session_id is not set, is /proc mounted with hidepid>0?

Thread 1 "light-locker" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff6ff2cef in g_log_structured_array () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) b
Breakpoint 1 at 0x7ffff6ff2cef
(gdb) bt
#0  0x00007ffff6ff2cef in g_log_structured_array () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff6ff2fb9 in g_log_default_handler () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6ff441a in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6ff4703 in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x0000555555560204 in  ()
#5  0x00007ffff710dfba in g_type_create_instance () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff70f50ed in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff70f634d in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff70f6e51 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x0000555555562b66 in gs_listener_new ()
#10 0x000055555555e648 in  ()
#11 0x00007ffff710dfba in g_type_create_instance () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff70f50ed in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff70f634d in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff70f6e51 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x000055555555eca7 in gs_monitor_new ()
#16 0x000055555555d4d1 in main ()

user@srv07:~/Desktop$ light-locker --debug
[gs_debug_init] gs-debug.c:106 (15:31:07):	 Debugging enabled
[main] light-locker.c:142 (15:31:07):	 initializing light-locker 1.8.0
[main] light-locker.c:143 (15:31:07):	 Platform:
gtk:        3
systemd:    yes
ConsoleKit: no
UPower:     yes
[main] light-locker.c:165 (15:31:07):	 Features:
lock-after-screensaver: yes
late-locking:           yes
lock-on-suspend:        yes
lock-on-lid:            yes
settings backend:       GSETTINGS
[main] light-locker.c:198 (15:31:07):	 lock after screensaver 0
[main] light-locker.c:199 (15:31:07):	 late locking 0
[main] light-locker.c:200 (15:31:07):	 lock on suspend 0
[main] light-locker.c:201 (15:31:07):	 lock on lid 0
[main] light-locker.c:202 (15:31:07):	 idle hint 0
[query_session_id] gs-listener-dbus.c:2101 (15:31:07):	 org.freedesktop.login1.NoSessionForPID raised:
 PID 855889 does not belong to any known session



** (light-locker:855889): ERROR **: 15:31:07.297: session_id is not set, is /proc mounted with hidepid>0?
Trace/breakpoint trap (core dumped)



user@srv07:~/Desktop$ ps -ef | grep light
root      757850       1  0 Apr11 ?        00:00:00 /usr/sbin/lightdm
root      757856  757850  1 Apr11 tty7     00:15:36 /usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
root      757915  757850  0 Apr11 ?        00:00:00 lightdm --session-child 13 20

```

**Comment by hinxx** [comment]
A reboot of the machine helped. Now the light-locker works as expected.
